#################################
# Dependabot Configuration File #
#################################

# This is the current version of the GitHub-native Dependabot
version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
