name: CD for vue package

on:
  repository_dispatch:
    types: [vocabulary-built]

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  deploy_npm:
    defaults:
      run:
        working-directory: "./"
    name: Deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install --no-audit

      - name: Publish package
        run: bash scripts/build_vue_vocabulary.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy
        run: bash publish/vue-vocabulary.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
