name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: "./"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run build
        run: npm run build:storybook
