name: Lint

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  lint:
    name: Lint
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run lint
        run: npm run lint
